server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: employee
          uri: http://employee:8080/employee
          predicates:
            Path=/employee/**
        - id: department
          uri: http://department:8080/department
          predicates:
            Path=/department/**
  security:
    oauth2:
      resource-server:
        opaque-token:
          introspection-uri: http://keycloak:8080/realms/cloud-gateway/protocol/openid-connect/token/introspect
          client-id: api-gateway
          client-secret: 2ixuJzGQkHdWbvxE5NGEY7IT9D2K9Znh

logging:
  level:
    root: info
    com.cuongnm.gateway: info
    org.apache.http: debug