apiVersion: v1
kind: Service
metadata:
  name: lab02-app2
spec:
  type: NodePort
  selector:
    app: lab02-app2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002