apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: default
data:
  keycloak.configuration.admin.username: admin
  keycloak.configuration.admin.password: admin
  keycloak.configuration.log.level: INFO
  keycloak.configuration.database.vendor: MYSQL
  keycloak.configuration.database.address: mysql-service
  keycloak.configuration.database.port: "3306"
  keycloak.configuration.database.name: keycloak
