apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: default
data:
  keycloak.configuration.admin.username: admin
  keycloak.configuration.admin.password: admin
  keycloak.configuration.log.level: INFO
  keycloak.configuration.database.vendor: mysql
  keycloak.configuration.database.address: "jdbc:mysql://mysql-service:3306/keycloak"
