server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: employee
          uri: http://localhost:8082/employee
          predicates:
            Path=/employee/**
  security:
    oauth2:
      resource-server:
        opaque-token:
          introspection-uri: http://localhost:30001/realms/cloud-gateway/protocol/openid-connect/token/introspect
          client-id: test
          client-secret: plZnvPUlQPQdc5XNno9FQtNtiwP1QnCO

logging:
  level:
    root: info
    com.cuongnm.gateway: debug
