server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: employee
          uri: http://localhost:8082/employee
          predicates:
            Path=/employee/**
#      default-filters:
#        - TokenRelay
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak-provider:
#            client-id: test
#            client-secret: plZnvPUlQPQdc5XNno9FQtNtiwP1QnCO
#            scope: openid
#        provider:
#          keycloak-provider:
#            issuer-uri: http://localhost:30001/realms/cloud-gateway
#            user-name-attribute: preferred_username

logging:
  level:
    root: info
    com.cuongnm.gateway: debug
