apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  selector:
    matchLabels:
      app: application
  replicas: 3
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: cuongnmdev/k8s-lab01:latest
          ports:
            - containerPort: 8080
          env:
            - name: SYS_APP_HOSTNAME
              value: application
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 1