apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  type: NodePort
  selector:
    app: application
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001