apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
      nodePort: 30001
    - protocol: TCP
      name: https
      port: 8443
      targetPort: 8443
      nodePort: 30002