apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: cuongnmdev/gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: spring.security.oauth2.resourceserver.opaquetoken.introspectionuri
              value: "http://keycloak:8080/realms/cloud-gateway/protocol/openid-connect/token/introspect"
            - name: spring.security.oauth2.resourceserver.opaquetoken.clientid
              value: "api-gateway"
            - name: spring.security.oauth2.resourceserver.opaquetoken.clientsecret
              value: "2ixuJzGQkHdWbvxE5NGEY7IT9D2K9Znh"