apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: cuongnmdev/gateway:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: gateway-config
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 5
#            periodSeconds: 10
#            timeoutSeconds: 3
#            failureThreshold: 1