apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  type: NodePort
  selector:
    app: application
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30001